package com.emonized.birthday.util

import com.emonized.birthday.R
import com.emonized.birthday.constant.AppConstant

class UIUtil {
    companion object{
        fun getImageIdList() : Array<Int>{

            return arrayOf(
                R.drawable.images_0,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.image_1,
                R.drawable.image_2,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.image_3,
                R.drawable.image_4,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.image_5,
                R.drawable.image_6,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.image_7,
                R.drawable.images_8,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.images_9,
                R.drawable.images_10,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.images_11,
                R.drawable.images_12,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.images_13,
                R.drawable.images_14,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.images_15,
                R.drawable.images_16,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.images_17,
                R.drawable.images_18,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.images_19,
                R.drawable.images_20,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.images_21,
                R.drawable.images_22,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.images_23,
                R.drawable.images_24,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.images_25,
                R.drawable.images_26,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.images_27,
                R.drawable.images_28,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.images_29,
                R.drawable.images_30,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.images_31,
                R.drawable.images_32,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.images_33,
                R.drawable.images_34,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.images_35
            )
        }

        fun getImagePrivateList() : Array<Int>{
            return arrayOf(
                R.drawable.image_private_1,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.image_private_2,
                R.drawable.image_private_3,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.image_private_4,
                R.drawable.image_private_5,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.image_private_6,
                R.drawable.image_private_7,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.image_private_8,
                R.drawable.image_private_9,
                AppConstant.EMPTY_IMAGE_ID,
                AppConstant.EMPTY_IMAGE_ID,
                R.drawable.image_private_10)
        }
    }
}